apiVersion: v1
kind: BuildConfig
metadata:
  name: java-cgxd
  labels:
    app: java-cgxd
    application: oshinko-java-spark
    createdBy: template-oshinko-java-build-dc
spec:
  triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: java-cgxd
    - type: Generic
      generic:
        secret: java-cgxd
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'https://github.com/radanalyticsio/spring-sparkpi'
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: radanalyticsio/radanalytics-java-spark
      env:
        - name: APP_FILE
          value: SparkPiBoot-0.0.1-SNAPSHOT.jar
      forcePull: true
  output:
    to:
      kind: ImageStreamTag
      name: 'java-cgxd:latest'
  resources: {}
  postCommit: {}
  nodeSelector: null
status:
  lastVersion: 1

