apiVersion: v1
kind: DeploymentConfig
metadata:
  name: java-cgxd
  labels:
    app: java-cgxd
    application: oshinko-java-spark
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
  replicas: 1
  test: false
  selector:
    deploymentconfig: java-cgxd
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-cgxd
        deploymentconfig: java-cgxd
    spec:
      containers:
        - name: java-cgxd
          image: development/java-cgxd
          env:
            - name: OSHINKO_CLUSTER_NAME
            - name: APP_ARGS
            - name: SPARK_OPTIONS
            - name: APP_MAIN_CLASS
            - name: OSHINKO_DEL_CLUSTER
              value: 'true'
            - name: APP_EXIT
              value: 'true'
            - name: OSHINKO_NAMED_CONFIG
            - name: OSHINKO_SPARK_DRIVER_CONFIG
          resources: {}
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: oshinko
      serviceAccount: oshinko
      securityContext: {}
